// src/app/token/[id]/page.tsx
"use client";

import { use, useState, useEffect, useCallback } from "react";
import { motion } from "framer-motion";
import Image from "next/image";
import Link from "next/link";
import { useQueryClient } from "@tanstack/react-query";
import {
	Globe,
	Twitter,
	Share2,
	Star,
	Copy,
	Check,
	TrendingUp,
	TrendingDown,
	MessageCircle,
	ExternalLink,
	Shield,
	Activity,
	Users,
	BarChart3,
	Clock,
	Info,
	ChevronDown,
	ChevronUp,
	Loader2,
	RefreshCw,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { PriceChart } from "@/components/charts";
import {
	TradeTape,
	TradingPanel,
	OnChainTradingPanel,
} from "@/components/trade";
import { BondingCurveProgress, TokenChat } from "@/components/token";
import { useToken, tokenKeys, useTokenHolders } from "@/hooks/useTokens";
import { useTokenTrades, tradeKeys } from "@/hooks/useTrades";
import { useWebSocket } from "@/hooks/useWebSocket";
import { useManualSync } from "@/hooks/useBlockchainSync";
import { usePersistedTabs } from "@/hooks/usePersistedTabs";
import {
	cn,
	formatMarketCap,
	formatVolume,
	formatPrice,
	fromWei,
} from "@/lib/utils";
import type { Address } from "viem";
import type { Token } from "@/types";

interface TokenDetailPageProps {
	params: Promise<{ id: string }>;
}

export default function TokenDetailPage({ params }: TokenDetailPageProps) {
	const { id } = use(params);
	const [copied, setCopied] = useState(false);
	const [showFullDescription, setShowFullDescription] = useState(false);
	const [isStarred, setIsStarred] = useState(false);

	const { data: token, isLoading, error } = useToken(id);
	const { data: tradesData } = useTokenTrades(id);

	// Ensure trades is always an array, even if data is undefined
	const trades = tradesData || [];

	console.log({ trades });
	const { data: holdersData, isLoading: holdersLoading } =
		useTokenHolders(id);
	const { sync: syncWithBlockchain, isSyncing } = useManualSync(id);
	const queryClient = useQueryClient();

	// Tab persistence with URL sync
	const { activeTab, setActiveTab } = usePersistedTabs({
		key: "tab",
		defaultTab: "trades" as const,
		validTabs: ["trades", "comments", "holders"] as const,
	});

	// Get holders from blockchain data
	const holders = holdersData?.holders || [];

	// Real-time updates via WebSocket
	const handleWebSocketMessage = useCallback(
		(message: any) => {
			if (
				message.channel === `trades:${id}` &&
				message.event === "trade_executed"
			) {
				// Invalidate trades query to refetch
				queryClient.invalidateQueries({
					queryKey: tradeKeys.byToken(id),
				});
				// Invalidate token detail to get updated stats
				queryClient.invalidateQueries({
					queryKey: tokenKeys.detail(id),
				});
				// Invalidate holders query to get updated count from blockchain
				queryClient.invalidateQueries({
					queryKey: tokenKeys.holders(id),
				});
			}
			if (
				message.channel === `price:${id}` &&
				message.event === "price_update"
			) {
				// Update token data optimistically with all stats including holdersCount and tradesCount
				queryClient.setQueryData(
					tokenKeys.detail(id),
					(oldData: Token | undefined) => {
						if (!oldData) return oldData;
						return {
							...oldData,
							currentPrice: message.data.price,
							marketCap: message.data.marketCap,
							priceChange24h:
								message.data.priceChange24h ??
								oldData.priceChange24h,
							// Update tradesCount in real-time
							tradesCount:
								message.data.tradesCount ?? oldData.tradesCount,
						};
					},
				);
			}
		},
		[id, queryClient],
	);

	const { isConnected, subscribe, unsubscribe } = useWebSocket({
		onMessage: handleWebSocketMessage,
	});

	// Subscribe to token-specific channels
	useEffect(() => {
		if (isConnected && id) {
			subscribe(`trades:${id}`);
			subscribe(`price:${id}`);

			return () => {
				unsubscribe(`trades:${id}`);
				unsubscribe(`price:${id}`);
			};
		}
	}, [isConnected, id, subscribe, unsubscribe]);

	// Format contract address for display
	const formatAddress = (address: string) => {
		if (!address) return "";
		return `${address.slice(0, 6)}...${address.slice(-4)}`;
	};

	// Get explorer URL for contract
	const getExplorerUrl = (address: string) => {
		return `https://amoy.polygonscan.com/address/${address}`;
	};

	const handleCopy = () => {
		if (!token) return;
		navigator.clipboard.writeText(token.id);
		setCopied(true);
		setTimeout(() => setCopied(false), 2000);
	};

	const handleShare = async () => {
		if (!token) return;
		const url = window.location.href;
		const text = `Check out $${token.symbol} on HypeMint!`;

		if (navigator.share) {
			try {
				await navigator.share({ title: token.name, text, url });
			} catch (e) {
				// User cancelled or error
			}
		} else {
			navigator.clipboard.writeText(url);
		}
	};

	// Calculate time since creation
	const getTimeSinceCreation = () => {
		if (!token?.createdAt) return "";
		const created = new Date(token.createdAt);
		const now = new Date();
		const diffMs = now.getTime() - created.getTime();
		const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
		const diffDays = Math.floor(diffHours / 24);

		if (diffDays > 0) return `${diffDays}d ago`;
		if (diffHours > 0) return `${diffHours}h ago`;
		return "Just now";
	};

	if (isLoading) {
		return (
			<div className="w-full mx-auto p-6 overflow-x-hidden">
				<div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_320px] xl:grid-cols-[minmax(0,1fr)_350px] gap-6">
					<div className="min-w-0 space-y-6">
						<Skeleton className="h-[438.51px] rounded-xl" />
						<Skeleton className="h-[443.28px] rounded-xl" />
						<Skeleton className="h-[35.99px] rounded-xl" />
						<Skeleton className="h-[347.31px] rounded-xl" />
					</div>
					<div className="space-y-6">
						<Skeleton className="h-[322.26px] rounded-xl" />
						<Skeleton className="h-[98.14px] rounded-xl" />
						<Skeleton className="h-[188.32px] rounded-xl" />
						<Skeleton className="h-[142.14px] rounded-xl" />
					</div>
				</div>
			</div>
		);
	}

	if (error || !token) {
		return (
			<div className="w-full mx-auto p-6 flex flex-col items-center justify-center min-h-[50vh] text-center">
				<h1 className="text-3xl font-bold mb-4">Token not found</h1>
				<p className="text-muted-foreground mb-6">
					The token you are looking for does not exist or has been
					removed.
				</p>
				<Link href="/">
					<Button>Return to Home</Button>
				</Link>
			</div>
		);
	}

	const pricePositive = (token.priceChange24h ?? 0) >= 0;

	return (
		<div className="w-full mx-auto p-3 sm:p-4 lg:p-6 relative overflow-x-clip">
			<div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_320px] xl:grid-cols-[minmax(0,1fr)_350px] relative gap-4 lg:gap-6">
				{/* Main Content */}
				<div className="min-w-0 space-y-4 sm:space-y-6">
					{/* Token Header */}
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						className="bg-card border border-border rounded-xl p-4 sm:p-6"
					>
						<div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
							<div className="flex items-center gap-3 sm:gap-4">
								<div className="w-12 h-12 sm:w-16 sm:h-16 rounded-xl bg-muted overflow-hidden shrink-0">
									{token.imageUrl ? (
										<Image
											src={token.imageUrl.replace(
												"0.0.0.0",
												"localhost",
											)}
											alt={token.name || "Token"}
											width={48}
											height={48}
											unoptimized
											className="object-cover w-full h-full"
										/>
									) : (
										<div className="w-full h-full flex items-center justify-center text-2xl font-bold text-muted-foreground">
											{token.symbol?.slice(0, 2) || "??"}
										</div>
									)}
								</div>

								<div className="min-w-0">
									<div className="flex flex-wrap items-center gap-1.5 sm:gap-2">
										<h1 className="text-lg sm:text-xl font-bold truncate">
											{token.name}
										</h1>
										<Badge
											variant="outline"
											className="text-xs"
										>
											{token.symbol}
										</Badge>
										{token.status === "active" && (
											<Badge className="bg-primary/20 text-primary text-xs">
												Live
											</Badge>
										)}
									</div>
									<div className="flex items-center gap-2 mt-1">
										<span className="text-xs text-muted-foreground">
											Created by
										</span>
										<Link
											href={`/user/${token.creator?.walletAddress || ""}`}
											className="text-xs text-primary hover:underline"
										>
											{token.creator?.displayName ||
												token.creator?.username ||
												(token.creator?.walletAddress
													? `${token.creator.walletAddress.slice(0, 6)}...`
													: "Unknown")}
										</Link>
										<span className="text-xs text-muted-foreground">
											{token.createdAt
												? new Date(
														token.createdAt,
													).toLocaleDateString()
												: ""}
										</span>
									</div>
								</div>
							</div>

							<div className="flex items-center gap-2 shrink-0">
								<Button
									variant="outline"
									size="icon"
									className="h-8 w-8 sm:h-9 sm:w-9"
									onClick={() => syncWithBlockchain()}
									disabled={isSyncing}
									title="Sync with blockchain"
								>
									<RefreshCw
										className={cn(
											"h-3.5 w-3.5 sm:h-4 sm:w-4",
											isSyncing && "animate-spin",
										)}
									/>
								</Button>
								<Button
									variant="outline"
									size="icon"
									className="h-8 w-8 sm:h-9 sm:w-9"
									onClick={handleShare}
								>
									<Share2 className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
								</Button>
								<Button
									variant="outline"
									size="icon"
									className={cn(
										"h-8 w-8 sm:h-9 sm:w-9",
										isStarred ? "text-yellow-500" : "",
									)}
									onClick={() => setIsStarred(!isStarred)}
								>
									<Star
										className={cn(
											"h-3.5 w-3.5 sm:h-4 sm:w-4",
											isStarred && "fill-current",
										)}
									/>
								</Button>
							</div>
						</div>

						{/* Token Badges */}
						<div className="flex flex-wrap items-center gap-2 mt-4">
							{token.hypeBoostEnabled && (
								<Badge className="bg-gradient-to-r from-purple-500 to-pink-500 text-white text-xs gap-1">
									<Shield className="h-3 w-3" />
									HypeBoost
								</Badge>
							)}
							<Badge variant="outline" className="text-xs gap-1">
								<Clock className="h-3 w-3" />
								{getTimeSinceCreation()}
							</Badge>
							{token.id && (
								<a
									href={getExplorerUrl(token.id)}
									target="_blank"
									rel="noopener noreferrer"
									className="inline-flex"
								>
									<Badge
										variant="outline"
										className="text-xs gap-1 hover:bg-muted cursor-pointer"
									>
										<ExternalLink className="h-3 w-3" />
										{formatAddress(token.id)}
									</Badge>
								</a>
							)}
						</div>

						{/* Description */}
						{token.description && (
							<div className="mt-4">
								<p
									className={cn(
										"text-sm text-muted-foreground",
										!showFullDescription && "line-clamp-2",
									)}
								>
									{token.description}
								</p>
								{token.description.length > 150 && (
									<button
										onClick={() =>
											setShowFullDescription(
												!showFullDescription,
											)
										}
										className="text-xs text-primary hover:underline mt-1 flex items-center gap-1"
									>
										{showFullDescription ? (
											<>
												Show less{" "}
												<ChevronUp className="h-3 w-3" />
											</>
										) : (
											<>
												Show more{" "}
												<ChevronDown className="h-3 w-3" />
											</>
										)}
									</button>
								)}
							</div>
						)}

						{/* Price Stats */}
						<div className="mt-6">
							<div className="flex items-baseline gap-2">
								<span className="text-muted-foreground text-sm">
									Market Cap
								</span>
							</div>
							<div className="flex flex-wrap items-baseline gap-2 sm:gap-3 mt-1">
								<span className="text-2xl sm:text-3xl font-bold">
									{formatMarketCap(token.marketCap)}
								</span>
								<span
									className={cn(
										"text-sm font-medium flex items-center gap-1",
										pricePositive
											? "text-[#00ff88]"
											: "text-destructive",
									)}
								>
									{pricePositive ? (
										<TrendingUp className="h-4 w-4" />
									) : (
										<TrendingDown className="h-4 w-4" />
									)}
									{pricePositive ? "+" : ""}
									{(token.priceChange24h ?? 0).toFixed(2)}%
									24hr
								</span>
							</div>
						</div>

						{/* Quick Stats */}
						<div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4 mt-4 sm:mt-6 pt-4 sm:pt-6 border-t border-border">
							<div>
								<p className="text-xs text-muted-foreground">
									Vol 24h
								</p>
								<p className="font-semibold tabular-nums">
									{formatVolume(token.volume24h)}
								</p>
							</div>
							<div>
								<p className="text-xs text-muted-foreground">
									Price
								</p>
								<p className="font-semibold tabular-nums">
									{formatPrice(token.currentPrice)}
								</p>
							</div>
							<div>
								<p className="text-xs text-muted-foreground">
									Holders
								</p>
								<p className="font-semibold tabular-nums">
									{holdersData?.totalHolders ?? 0}
								</p>
							</div>
							<div>
								<p className="text-xs text-muted-foreground">
									Trades
								</p>
								<p className="font-semibold tabular-nums">
									{token.tradesCount ?? 0}
								</p>
							</div>
						</div>

						{/* Social Links */}
						<div className="flex flex-wrap items-center gap-2 sm:gap-3 mt-4 sm:mt-6 pt-4 sm:pt-6 border-t border-border">
							{token.websiteUrl && (
								<a
									href={token.websiteUrl}
									target="_blank"
									rel="noopener noreferrer"
									className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-muted/50 text-xs text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
								>
									<Globe className="h-3.5 w-3.5" />
									Website
								</a>
							)}
							{token.twitterUrl && (
								<a
									href={token.twitterUrl}
									target="_blank"
									rel="noopener noreferrer"
									className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-muted/50 text-xs text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
								>
									<Twitter className="h-3.5 w-3.5" />
									Twitter
								</a>
							)}
							{token.telegramUrl && (
								<a
									href={token.telegramUrl}
									target="_blank"
									rel="noopener noreferrer"
									className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-muted/50 text-xs text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
								>
									<MessageCircle className="h-3.5 w-3.5" />
									Telegram
								</a>
							)}
							<Button
								variant="ghost"
								size="sm"
								onClick={handleCopy}
								className="h-7 text-xs gap-1.5 rounded-full"
							>
								{copied ? (
									<Check className="h-3.5 w-3.5 text-green-500" />
								) : (
									<Copy className="h-3.5 w-3.5" />
								)}
								{copied ? "Copied!" : "Copy Address"}
							</Button>
						</div>
					</motion.div>

					{/* Price Chart */}
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						transition={{ delay: 0.1 }}
					>
						<PriceChart tokenId={id} />
					</motion.div>

					{/* Comments / Trades / Holders Tabs */}
					<motion.div
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						transition={{ delay: 0.2 }}
					>
						<Tabs
							value={activeTab}
							onValueChange={(value) =>
								setActiveTab(
									value as "trades" | "comments" | "holders",
								)
							}
						>
							<TabsList className="w-full bg-card border border-border">
								<TabsTrigger
									value="trades"
									className="flex-1 gap-1.5"
								>
									<BarChart3 className="h-3.5 w-3.5" />
									Trades
								</TabsTrigger>
								<TabsTrigger
									value="comments"
									className="flex-1 gap-1.5"
								>
									<MessageCircle className="h-3.5 w-3.5" />
									Comments
								</TabsTrigger>
								<TabsTrigger
									value="holders"
									className="flex-1 gap-1.5"
								>
									<Users className="h-3.5 w-3.5" />
									Holders{" "}
									{holdersData?.totalHolders
										? `(${holdersData.totalHolders})`
										: ""}
								</TabsTrigger>
							</TabsList>
							<TabsContent value="trades" className="mt-4">
								<TradeTape
									tokenId={id}
									initialTrades={trades}
								/>
							</TabsContent>
							<TabsContent value="comments" className="mt-4">
								<TokenChat
									tokenId={id}
									className="min-h-[350px]"
								/>
							</TabsContent>
							<TabsContent value="holders" className="mt-4">
								<div className="bg-card border border-border rounded-xl p-6">
									{holdersLoading ? (
										<div className="text-center py-12">
											<Loader2 className="h-12 w-12 mx-auto text-primary animate-spin mb-4" />
											<p className="text-muted-foreground">
												Loading holders from
												blockchain...
											</p>
											<p className="text-xs text-muted-foreground mt-1">
												Scanning Transfer events
											</p>
										</div>
									) : holders.length > 0 ? (
										<div className="space-y-3">
											{holders.map((holder, index) => (
												<div
													key={holder.address}
													className="flex items-center justify-between py-2 border-b border-border/50 last:border-0"
												>
													<div className="flex items-center gap-3">
														<span
															className={cn(
																"w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold",
																index === 0
																	? "bg-yellow-500/20 text-yellow-500"
																	: index ===
																		  1
																		? "bg-gray-400/20 text-gray-400"
																		: index ===
																			  2
																			? "bg-orange-500/20 text-orange-500"
																			: "bg-muted text-muted-foreground",
															)}
														>
															{index + 1}
														</span>
														<div>
															<Link
																href={`/user/${holder.address}`}
																className="font-mono text-sm hover:text-primary"
															>
																{formatAddress(
																	holder.address,
																)}
															</Link>
															<p className="text-xs text-muted-foreground">
																{holder.balanceFormatted.toLocaleString(
																	undefined,
																	{
																		maximumFractionDigits: 2,
																	},
																)}{" "}
																tokens
															</p>
														</div>
													</div>
													<div className="text-right">
														<span className="font-semibold tabular-nums">
															{holder.percentage.toFixed(
																2,
															)}
															%
														</span>
														<div className="w-20 h-1.5 bg-muted rounded-full mt-1">
															<div
																className="h-full bg-primary rounded-full"
																style={{
																	width: `${Math.min(holder.percentage, 100)}%`,
																}}
															/>
														</div>
													</div>
												</div>
											))}
										</div>
									) : (
										<div className="text-center py-12">
											<Users className="h-12 w-12 mx-auto text-muted-foreground/50 mb-4" />
											<p className="text-muted-foreground">
												No holders data available yet
											</p>
											<p className="text-xs text-muted-foreground mt-1">
												Holder data will appear after
												trading begins
											</p>
										</div>
									)}
								</div>
							</TabsContent>
						</Tabs>
					</motion.div>
				</div>

				{/* Sidebar */}
				<div className="min-w-0 w-full sticky top-30 space-y-4 sm:space-y-6 overflow-hidden">
					{/* Trading Panel - On-Chain or Centralized */}
					<motion.div
						initial={{ opacity: 0, x: 20 }}
						animate={{ opacity: 1, x: 0 }}
					>
						{token.bondingCurveAddress && token.contractAddress ? (
							<OnChainTradingPanel
								tokenAddress={token.contractAddress as Address}
								bondingCurveAddress={
									token.bondingCurveAddress as Address
								}
								tokenSymbol={token.symbol || "TOKEN"}
								tokenName={token.name || "Unknown Token"}
								currentPrice={token.currentPrice || "0.00001"}
							/>
						) : (
							<TradingPanel
								tokenId={id}
								tokenSymbol={token.symbol || "TOKEN"}
								tokenName={token.name || "Unknown Token"}
								currentPrice={token.currentPrice || "0.00001"}
								totalSupply={token.totalSupply || "1000000000"}
							/>
						)}
					</motion.div>

					{/* Bonding Curve */}
					<motion.div
						initial={{ opacity: 0, x: 20 }}
						animate={{ opacity: 1, x: 0 }}
						transition={{ delay: 0.1 }}
						className="bg-card border border-border rounded-xl p-4"
					>
						<BondingCurveProgress
							progress={token.bondingCurveProgress ?? 0}
							currentAmount={token.currentBondingAmount || "0"}
							targetAmount={token.graduationTarget || "100"}
						/>
					</motion.div>

					{/* Token Info */}
					<motion.div
						initial={{ opacity: 0, x: 20 }}
						animate={{ opacity: 1, x: 0 }}
						transition={{ delay: 0.2 }}
						className="bg-card border border-border rounded-xl p-4"
					>
						<div className="flex items-center gap-2 mb-4">
							<Info className="h-4 w-4 text-muted-foreground" />
							<span className="font-semibold text-sm">
								Token Info
							</span>
						</div>
						<div className="space-y-3">
							<div className="flex items-center justify-between">
								<span className="text-xs text-muted-foreground">
									Total Supply
								</span>
								<span className="text-sm font-mono tabular-nums">
									{parseFloat(
										token.totalSupply || "1000000000",
									).toLocaleString()}
								</span>
							</div>
							<div className="flex items-center justify-between">
								<span className="text-xs text-muted-foreground">
									Circulating
								</span>
								<span className="text-sm font-mono tabular-nums">
									{parseFloat(
										token.circulatingSupply || "0",
									).toLocaleString()}
								</span>
							</div>
							<div className="flex items-center justify-between">
								<span className="text-xs text-muted-foreground">
									Reserve
								</span>
								<span className="text-sm font-mono tabular-nums">
									{fromWei(
										token.currentBondingAmount || "0",
									).toFixed(4)}{" "}
									POL
								</span>
							</div>
							<div className="flex items-center justify-between">
								<span className="text-xs text-muted-foreground">
									Network
								</span>
								<Badge variant="outline" className="text-xs">
									Polygon Amoy
								</Badge>
							</div>
							{token.hypeBoostEnabled && (
								<>
									<div className="border-t border-border pt-3 mt-3">
										<div className="flex items-center gap-1.5 text-xs text-muted-foreground mb-2">
											<Shield className="h-3.5 w-3.5 text-purple-500" />
											<span>HypeBoost Protection</span>
										</div>
										<div className="grid grid-cols-2 gap-2 text-xs">
											<div className="bg-muted/50 rounded-lg p-2">
												<p className="text-muted-foreground">
													Max Wallet
												</p>
												<p className="font-medium">
													2%
												</p>
											</div>
											<div className="bg-muted/50 rounded-lg p-2">
												<p className="text-muted-foreground">
													Snipe Protection
												</p>
												<p className="font-medium">
													5 blocks
												</p>
											</div>
										</div>
									</div>
								</>
							)}
						</div>
					</motion.div>

					{/* Quick Stats - Activity Section */}
					<motion.div
						initial={{ opacity: 0, x: 20 }}
						animate={{ opacity: 1, x: 0 }}
						transition={{ delay: 0.3 }}
						className="bg-card border border-border rounded-xl p-4"
					>
						<div className="flex items-center gap-2 mb-4">
							<Activity className="h-4 w-4 text-muted-foreground" />
							<span className="font-semibold text-sm">
								Activity
							</span>
						</div>
						<div className="grid grid-cols-2 gap-3">
							<div className="bg-muted/30 rounded-lg p-3 text-center">
								<p className="text-2xl font-bold tabular-nums">
									{holdersData?.totalHolders ?? 0}
								</p>
								<p className="text-xs text-muted-foreground">
									Holders
								</p>
							</div>
							<div className="bg-muted/30 rounded-lg p-3 text-center">
								<p className="text-2xl font-bold tabular-nums">
									{token.tradesCount ?? 0}
								</p>
								<p className="text-xs text-muted-foreground">
									Trades
								</p>
							</div>
						</div>
					</motion.div>
				</div>
			</div>
		</div>
	);
}

// src/routes/tokens/[id]/+page.svelte
<script lang="ts">
  import { page } from '$app/stores'
  import { goto } from '$app/navigation'
  import { onMount } from 'svelte'
  import { isAuthenticated, wallet } from '$lib/stores'
  import { toasts } from '$lib/stores/toast'
  import { blockchain, type TokenInfo, type CurveAnalytics, type TradeQuote } from '$lib/contracts'
  import PriceChart from '$lib/components/PriceChart.svelte'
  import Comments from '$lib/components/Comments.svelte'
  import TradesFeed from '$lib/components/TradesFeed.svelte'
  import { ArrowLeft, AlertTriangle, RefreshCw, Copy, ExternalLink, TrendingUp, BarChart3, Users, Activity, Globe, Twitter, Send, User, ChevronRight, Loader2, LineChart, MessageSquare, ArrowUpDown } from 'lucide-svelte'

  let tokenAddress = $derived($page.params.id)
  let token = $state<TokenInfo | null>(null)
  let analytics = $state<CurveAnalytics | null>(null)
  let loading = $state(true)
  let error = $state<string | null>(null)

  // Trading state
  let tradeType = $state<'buy' | 'sell'>('buy')
  let amount = $state('')
  let quote = $state<TradeQuote | null>(null)
  let tradeLoading = $state(false)
  let quoteLoading = $state(false)
  let userBalance = $state('0')

  // Tab state
  let activeTab = $state<'chart' | 'trades' | 'comments'>('chart')

  onMount(async () => {
    await loadToken()
  })

  async function loadToken() {
    if (!tokenAddress) {
      error = 'No token address provided'
      loading = false
      return
    }
    loading = true
    error = null
    try {
      token = await blockchain.getTokenInfo(tokenAddress)
      if (token?.curveAddress) {
        analytics = await blockchain.getCurveAnalytics(token.curveAddress)
      }
      if ($wallet.address && token?.tokenAddress) {
        userBalance = await blockchain.getTokenBalance(token.tokenAddress, $wallet.address)
      }
    } catch (err: any) {
      console.error('Failed to load token:', err)
      error = err.message || 'Failed to load token data'
    } finally {
      loading = false
    }
  }

  async function updateQuote() {
    if (!token?.curveAddress || !amount || parseFloat(amount) <= 0) {
      quote = null
      return
    }

    quoteLoading = true
    try {
      if (tradeType === 'buy') {
        quote = await blockchain.getBuyQuote(token.curveAddress, amount)
      } else {
        quote = await blockchain.getSellQuote(token.curveAddress, amount)
      }
    } catch (err) {
      console.error('Quote error:', err)
      quote = null
    } finally {
      quoteLoading = false
    }
  }

  // Debounced quote update
  let quoteTimeout: ReturnType<typeof setTimeout>
  $effect(() => {
    amount; tradeType;
    clearTimeout(quoteTimeout)
    quoteTimeout = setTimeout(updateQuote, 300)
  })

  async function handleTrade() {
    if (!$isAuthenticated || !$wallet.address) {
      toasts.warning('Please connect wallet first')
      return
    }

    if (!token?.curveAddress || !token?.tokenAddress) {
      toasts.error('Invalid token')
      return
    }

    if (!amount || parseFloat(amount) <= 0) {
      toasts.error('Enter a valid amount')
      return
    }

    tradeLoading = true
    try {
      let txHash: string
      if (tradeType === 'buy') {
        const minTokens = quote?.tokensOut 
          ? (parseFloat(quote.tokensOut) * 0.95).toString()
          : '0'
        txHash = await blockchain.buyTokens(token.curveAddress, amount, minTokens)
        toasts.success(`Bought ${token.symbol}! Tx: ${txHash.slice(0, 10)}...`)
      } else {
        const minEth = quote?.ethOut
          ? (parseFloat(quote.ethOut) * 0.95).toString()
          : '0'
        txHash = await blockchain.sellTokens(token.tokenAddress, token.curveAddress, amount, minEth)
        toasts.success(`Sold ${token.symbol}! Tx: ${txHash.slice(0, 10)}...`)
      }
      
      amount = ''
      quote = null
      await loadToken()
    } catch (err: any) {
      console.error('Trade failed:', err)
      toasts.error(err.message || 'Trade failed')
    } finally {
      tradeLoading = false
    }
  }

  function formatNumber(num: string | number, decimals: number = 2): string {
    const n = typeof num === 'string' ? parseFloat(num) : num
    if (isNaN(n)) return '0'
    if (n >= 1000000) return `${(n / 1000000).toFixed(decimals)}M`
    if (n >= 1000) return `${(n / 1000).toFixed(decimals)}K`
    return n.toFixed(decimals)
  }

  function formatPrice(price: string | number): string {
    const p = typeof price === 'string' ? parseFloat(price) : price
    if (isNaN(p) || p === 0) return '$0.000000'
    if (p < 0.000001) return `$${p.toExponential(2)}`
    if (p < 0.01) return `$${p.toFixed(6)}`
    return `$${p.toFixed(4)}`
  }

  function shortenAddress(addr: string): string {
    if (!addr) return ''
    return `${addr.slice(0, 6)}...${addr.slice(-4)}`
  }

  function copyAddress(addr: string) {
    navigator.clipboard.writeText(addr)
    toasts.success('Address copied!')
  }
</script>

<svelte:head>
  <title>{token?.name || 'Loading...'} | HypeMint</title>
</svelte:head>

<div class="container">
  <div class="back-nav">
    <a href="/tokens" class="back-link">
      <ArrowLeft size={18} />
      <span>Back to Tokens</span>
    </a>
  </div>

  {#if loading}
    <div class="loading-state">
      <Loader2 size={32} class="spin" />
      <p>Loading token data...</p>
    </div>
  {:else if error}
    <div class="error-state card">
      <div class="error-icon">
        <AlertTriangle size={32} />
      </div>
      <h2>Failed to Load Token</h2>
      <p>{error}</p>
      <button class="btn btn-primary" onclick={loadToken}>
        <RefreshCw size={16} />
        <span>Try Again</span>
      </button>
    </div>
  {:else if token}
    <div class="token-page">
      <div class="main-content">
        <div class="token-header card">
          <div class="header-left">
            <div class="token-avatar">
              {#if token.imageUrl}
                <img src={token.imageUrl} alt={token.name} />
              {:else}
                <span class="avatar-text">{token.symbol.slice(0, 2)}</span>
              {/if}
            </div>
            <div class="token-info">
              <div class="token-name-row">
                <h1>{token.name}</h1>
                <span class="symbol">${token.symbol}</span>
                {#if token.graduated}
                  <span class="badge graduated">Graduated</span>
                {/if}
              </div>
              <div class="token-address">
                <button class="copy-address" onclick={() => copyAddress(token?.tokenAddress || '')}>
                  <span>{shortenAddress(token.tokenAddress)}</span>
                  <Copy size={14} />
                </button>
                <a href={`https://polygonscan.com/token/${token.tokenAddress}`} target="_blank" rel="noopener" class="external-link">
                  <ExternalLink size={14} />
                </a>
              </div>
            </div>
          </div>
          <div class="header-right">
            <div class="current-price">{formatPrice(token.currentPrice)}</div>
            <div class="price-change positive">+0.00%</div>
          </div>
        </div>

        <div class="stats-grid">
          <div class="stat-card card">
            <div class="stat-icon"><TrendingUp size={20} /></div>
            <div class="stat-content">
              <span class="stat-label">Market Cap</span>
              <span class="stat-value">${formatNumber(token.marketCap)}</span>
            </div>
          </div>
          <div class="stat-card card">
            <div class="stat-icon">💹</div>
            <div class="stat-content">
              <span class="stat-label">Volume</span>
              <span class="stat-value">${formatNumber(analytics?.totalVolume || '0')}</span>
            </div>
          </div>
          <div class="stat-card card">
            <div class="stat-icon">👥</div>
            <div class="stat-content">
              <span class="stat-label">Holders</span>
              <span class="stat-value">{analytics?.uniqueHolders || 0}</span>
            </div>
          </div>
          <div class="stat-card card">
            <div class="stat-icon">🔄</div>
            <div class="stat-content">
              <span class="stat-label">Trades</span>
              <span class="stat-value">{(analytics?.buyCount || 0) + (analytics?.sellCount || 0)}</span>
            </div>
          </div>
        </div>

        <div class="content-tabs">
          <button class="tab" class:active={activeTab === 'chart'} onclick={() => activeTab = 'chart'}>
            <LineChart size={16} />
            <span>Chart</span>
          </button>
          <button class="tab" class:active={activeTab === 'trades'} onclick={() => activeTab = 'trades'}>
            <ArrowUpDown size={16} />
            <span>Trades</span>
          </button>
          <button class="tab" class:active={activeTab === 'comments'} onclick={() => activeTab = 'comments'}>
            <MessageSquare size={16} />
            <span>Comments</span>
          </button>
        </div>

        <div class="tab-content">
          {#if activeTab === 'chart'}
            <div class="chart-container card">
              <PriceChart tokenSymbol={token.symbol} />
            </div>
          {:else if activeTab === 'trades'}
            <div class="trades-container">
              <TradesFeed tokenSymbol={token.symbol} />
            </div>
          {:else if activeTab === 'comments'}
            <Comments tokenId={token.tokenAddress} />
          {/if}
        </div>

        {#if token.description}
          <div class="about-section card">
            <h3>About {token.name}</h3>
            <p class="description">{token.description}</p>
            
            <div class="social-links">
              {#if token.twitterUrl}
                <a href={token.twitterUrl} target="_blank" rel="noopener" class="social-link twitter">
                  <Twitter size={16} />
                  <span>Twitter</span>
                </a>
              {/if}
              {#if token.telegramUrl}
                <a href={token.telegramUrl} target="_blank" rel="noopener" class="social-link telegram">
                  <Send size={16} />
                  <span>Telegram</span>
                </a>
              {/if}
              {#if token.websiteUrl}
                <a href={token.websiteUrl} target="_blank" rel="noopener" class="social-link website">
                  <Globe size={16} />
                  <span>Website</span>
                </a>
              {/if}
            </div>
          </div>
        {/if}

        <div class="creator-section card">
          <h3><User size={18} /> Creator</h3>
          <div class="creator-address">
            <button class="copy-address" onclick={() => copyAddress(token?.creator || '')}>
              <span>{shortenAddress(token.creator)}</span>
              <Copy size={14} />
            </button>
            <a href={`https://polygonscan.com/address/${token.creator}`} target="_blank" rel="noopener" class="external-link">
              <span>View on Polygonscan</span>
              <ExternalLink size={14} />
            </a>
          </div>
        </div>
      </div>

      <div class="trade-sidebar">
        <div class="trade-panel card sticky">
          <h3>Trade {token.symbol}</h3>
          
          <div class="trade-tabs">
            <button class="trade-tab buy" class:active={tradeType === 'buy'} onclick={() => { tradeType = 'buy'; amount = ''; quote = null; }}>
              <span class="tab-dot buy"></span>
              <span>Buy</span>
            </button>
            <button class="trade-tab sell" class:active={tradeType === 'sell'} onclick={() => { tradeType = 'sell'; amount = ''; quote = null; }}>
              <span class="tab-dot sell"></span>
              <span>Sell</span>
            </button>
          </div>

          <div class="trade-form">
            <div class="form-group">
              <div class="input-header">
                <label>{tradeType === 'buy' ? 'POL Amount' : `${token.symbol} Amount`}</label>
                {#if tradeType === 'sell'}
                  <span class="balance">Balance: {formatNumber(userBalance, 4)}</span>
                {/if}
              </div>
              <div class="input-wrapper">
                <input type="number" placeholder="0.0" bind:value={amount} step="0.001" min="0" />
                <span class="input-suffix">{tradeType === 'buy' ? 'POL' : token.symbol}</span>
              </div>
              {#if tradeType === 'sell'}
                <div class="quick-amounts">
                  <button onclick={() => amount = (parseFloat(userBalance) * 0.25).toString()}>25%</button>
                  <button onclick={() => amount = (parseFloat(userBalance) * 0.5).toString()}>50%</button>
                  <button onclick={() => amount = (parseFloat(userBalance) * 0.75).toString()}>75%</button>
                  <button onclick={() => amount = userBalance}>Max</button>
                </div>
              {/if}
            </div>

            {#if quote}
              <div class="quote-details">
                <div class="quote-row">
                  <span>You'll {tradeType === 'buy' ? 'receive' : 'get'}</span>
                  <span class="quote-value">
                    {tradeType === 'buy' 
                      ? `${formatNumber(quote.tokensOut || '0', 4)} ${token.symbol}`
                      : `${formatNumber(quote.ethOut || '0', 6)} POL`
                    }
                  </span>
                </div>
                <div class="quote-row">
                  <span>Fee (1%)</span>
                  <span class="quote-value">{formatNumber(quote.fee, 6)} POL</span>
                </div>
                <div class="quote-row">
                  <span>Price Impact</span>
                  <span class="quote-value" class:high-impact={quote.priceImpact > 5}>{quote.priceImpact.toFixed(2)}%</span>
                </div>
              </div>
            {/if}

            <button class="btn btn-trade {tradeType}" onclick={handleTrade} disabled={tradeLoading || !$isAuthenticated || !amount || parseFloat(amount) <= 0}>
              {#if tradeLoading}
                <Loader2 size={16} class="spin" />
                <span>Processing...</span>
              {:else if !$isAuthenticated}
                Connect Wallet
              {:else if quoteLoading}
                Getting quote...
              {:else}
                <span class="btn-dot {tradeType}"></span>
                <span>{tradeType === 'buy' ? 'Buy' : 'Sell'} {token.symbol}</span>
              {/if}
            </button>
          </div>

          {#if !token.graduated}
            <div class="graduation-progress">
              <div class="progress-header">
                <span class="progress-title">
                  <TrendingUp size={16} />
                  <span>Graduation Progress</span>
                </span>
                <span class="progress-percent">{Math.min(100, (parseFloat(token.marketCap) / 69000 * 100)).toFixed(1)}%</span>
              </div>
              <div class="progress-bar">
                <div class="progress-fill" style="width: {Math.min(100, (parseFloat(token.marketCap) / 69000 * 100))}%"></div>
              </div>
              <p class="progress-text">${formatNumber(token.marketCap)} / $69K to DEX listing</p>
            </div>
          {:else}
            <div class="graduated-badge">
              <span class="badge-icon"><TrendingUp size={20} /></span>
              <span>Listed on DEX!</span>
            </div>
          {/if}
        </div>
      </div>
    </div>
  {/if}
</div>

<style>
  .container { max-width: 1400px; margin: 0 auto; padding: 0 1rem; }
  .back-nav { padding: 1rem 0; }
  .back-link { display: inline-flex; align-items: center; gap: 0.5rem; color: var(--text-secondary); text-decoration: none; transition: color 0.2s; }
  .back-link:hover { color: var(--accent); }

  .loading-state { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 400px; gap: 1rem; }
  .spinner { width: 40px; height: 40px; border: 3px solid var(--border); border-top-color: var(--accent); border-radius: 50%; animation: spin 1s linear infinite; }
  @keyframes spin { to { transform: rotate(360deg); } }

  .error-state { text-align: center; padding: 3rem; }
  .error-icon { font-size: 3rem; margin-bottom: 1rem; }
  .error-state h2 { margin-bottom: 0.5rem; }
  .error-state p { color: var(--text-secondary); margin-bottom: 1.5rem; }

  .token-page { display: grid; grid-template-columns: 1fr 380px; gap: 2rem; padding-bottom: 3rem; }
  .token-header { display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem; }
  .header-left { display: flex; align-items: center; gap: 1rem; }
  .token-avatar { width: 72px; height: 72px; border-radius: 50%; background: var(--gradient-1); display: flex; align-items: center; justify-content: center; overflow: hidden; flex-shrink: 0; }
  .token-avatar img { width: 100%; height: 100%; object-fit: cover; }
  .avatar-text { font-size: 1.5rem; font-weight: 700; color: white; }
  .token-name-row { display: flex; align-items: center; gap: 0.75rem; flex-wrap: wrap; }
  .token-name-row h1 { font-size: 1.75rem; margin: 0; }
  .symbol { color: var(--text-secondary); font-size: 1rem; }
  .badge { font-size: 0.75rem; padding: 0.25rem 0.5rem; border-radius: var(--radius-sm); background: var(--success); color: white; }
  .token-address { display: flex; align-items: center; gap: 0.5rem; margin-top: 0.25rem; color: var(--text-secondary); font-size: 0.875rem; font-family: 'JetBrains Mono', monospace; }
  .token-address span { cursor: pointer; }
  .token-address span:hover { color: var(--accent); }
  .external-link { color: var(--accent); text-decoration: none; }
  .header-right { text-align: right; }
  .current-price { font-size: 1.75rem; font-weight: 700; font-family: 'JetBrains Mono', monospace; }
  .price-change { font-size: 0.875rem; font-weight: 600; }
  .positive { color: var(--success); }
  .negative { color: var(--error); }

  .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin: 1.5rem 0; }
  .stat-card { display: flex; align-items: center; gap: 0.75rem; padding: 1rem; }
  .stat-icon { font-size: 1.5rem; }
  .stat-label { display: block; font-size: 0.75rem; color: var(--text-muted); }
  .stat-value { font-size: 1.125rem; font-weight: 600; font-family: 'JetBrains Mono', monospace; }

  .content-tabs { display: flex; gap: 0.5rem; margin-bottom: 1rem; }
  .tab { padding: 0.75rem 1.25rem; background: var(--bg-tertiary); border: 1px solid var(--border); border-radius: var(--radius-sm); color: var(--text-secondary); cursor: pointer; transition: all 0.2s; font-weight: 500; font-size: 0.875rem; }
  .tab:hover { background: var(--border); }
  .tab.active { background: var(--accent); color: white; border-color: var(--accent); }
  .chart-container { padding: 0; overflow: hidden; }

  .about-section h3 { margin-bottom: 1rem; }
  .description { color: var(--text-secondary); line-height: 1.6; margin-bottom: 1rem; }
  .social-links { display: flex; gap: 0.75rem; flex-wrap: wrap; }
  .social-link { display: inline-flex; align-items: center; gap: 0.5rem; padding: 0.5rem 1rem; background: var(--bg-tertiary); border: 1px solid var(--border); border-radius: var(--radius-sm); color: var(--text-secondary); text-decoration: none; font-size: 0.875rem; transition: all 0.2s; }
  .social-link:hover { background: var(--border); color: var(--text-primary); }
  .social-link.twitter:hover { color: #1DA1F2; }
  .social-link.telegram:hover { color: #0088cc; }

  .creator-section h3 { margin-bottom: 0.75rem; }
  .creator-address { display: flex; align-items: center; gap: 1rem; font-family: 'JetBrains Mono', monospace; color: var(--text-secondary); }
  .creator-address span { cursor: pointer; }
  .creator-address span:hover { color: var(--accent); }

  .trade-sidebar { position: relative; }
  .trade-panel.sticky { position: sticky; top: 1rem; }
  .trade-panel h3 { margin-bottom: 1rem; text-align: center; }
  .trade-tabs { display: grid; grid-template-columns: 1fr 1fr; gap: 0.5rem; margin-bottom: 1.5rem; }
  .trade-tab { padding: 0.75rem; border: 2px solid var(--border); border-radius: var(--radius-sm); background: var(--bg-tertiary); cursor: pointer; font-weight: 600; transition: all 0.2s; }
  .trade-tab.buy:hover, .trade-tab.buy.active { border-color: var(--success); background: rgba(16, 185, 129, 0.1); }
  .trade-tab.sell:hover, .trade-tab.sell.active { border-color: var(--error); background: rgba(239, 68, 68, 0.1); }

  .trade-form { display: flex; flex-direction: column; gap: 1rem; }
  .input-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }
  .balance { font-size: 0.75rem; color: var(--text-muted); }
  .input-wrapper { display: flex; align-items: center; background: var(--bg-tertiary); border: 1px solid var(--border); border-radius: var(--radius-sm); overflow: hidden; }
  .input-wrapper input { flex: 1; background: transparent; border: none; padding: 0.75rem; font-size: 1.125rem; font-family: 'JetBrains Mono', monospace; }
  .input-wrapper input:focus { outline: none; }
  .input-suffix { padding: 0.75rem; color: var(--text-muted); font-weight: 500; border-left: 1px solid var(--border); background: var(--bg-secondary); }
  .quick-amounts { display: flex; gap: 0.5rem; margin-top: 0.5rem; }
  .quick-amounts button { flex: 1; padding: 0.5rem; background: var(--bg-tertiary); border: 1px solid var(--border); border-radius: var(--radius-sm); color: var(--text-secondary); font-size: 0.75rem; cursor: pointer; transition: all 0.2s; }
  .quick-amounts button:hover { background: var(--border); color: var(--text-primary); }

  .quote-details { background: var(--bg-tertiary); border-radius: var(--radius-sm); padding: 1rem; }
  .quote-row { display: flex; justify-content: space-between; padding: 0.25rem 0; font-size: 0.875rem; color: var(--text-secondary); }
  .quote-value { font-weight: 500; font-family: 'JetBrains Mono', monospace; color: var(--text-primary); }
  .high-impact { color: var(--warning) !important; }

  .btn-trade { width: 100%; padding: 1rem; font-size: 1rem; font-weight: 600; border: none; border-radius: var(--radius-sm); cursor: pointer; transition: all 0.2s; display: flex; align-items: center; justify-content: center; gap: 0.5rem; }
  .btn-trade.buy { background: var(--success); color: white; }
  .btn-trade.buy:hover:not(:disabled) { background: #059669; }
  .btn-trade.sell { background: var(--error); color: white; }
  .btn-trade.sell:hover:not(:disabled) { background: #dc2626; }
  .btn-trade:disabled { opacity: 0.5; cursor: not-allowed; }
  .spinner-sm { width: 16px; height: 16px; border: 2px solid transparent; border-top-color: currentColor; border-radius: 50%; animation: spin 0.8s linear infinite; }

  .graduation-progress { margin-top: 1.5rem; padding-top: 1.5rem; border-top: 1px solid var(--border); }
  .progress-header { display: flex; justify-content: space-between; margin-bottom: 0.5rem; font-size: 0.875rem; }
  .progress-percent { font-weight: 600; color: var(--accent); }
  .progress-bar { height: 8px; background: var(--bg-tertiary); border-radius: 4px; overflow: hidden; }
  .progress-fill { height: 100%; background: var(--gradient-1); border-radius: 4px; transition: width 0.3s ease; }
  .progress-text { margin-top: 0.5rem; font-size: 0.75rem; color: var(--text-muted); text-align: center; }
  .graduated-badge { margin-top: 1.5rem; padding: 1rem; background: rgba(16, 185, 129, 0.1); border: 1px solid var(--success); border-radius: var(--radius-sm); display: flex; align-items: center; justify-content: center; gap: 0.5rem; color: var(--success); font-weight: 600; }
  .badge-icon { font-size: 1.25rem; }

  @media (max-width: 1024px) { .token-page { grid-template-columns: 1fr; } .trade-panel.sticky { position: static; } .stats-grid { grid-template-columns: repeat(2, 1fr); } }
  @media (max-width: 600px) { .token-header { flex-direction: column; align-items: flex-start; } .header-right { text-align: left; } .stats-grid { grid-template-columns: 1fr; } .content-tabs { overflow-x: auto; } }
</style>
